# Generated by Django 4.0 on 2022-07-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('github_username', models.CharField(db_index=True, max_length=256, unique=True)),
                ('email', models.CharField(db_index=True, max_length=256, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='todo', max_length=16)),
                ('story_points', models.PositiveSmallIntegerField(default=1)),
                ('date_opened', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(related_name='task_assignees', to='root_app.User')),
                ('labels', models.ManyToManyField(related_name='task_labels', to='root_app.Label')),
                ('reviewers', models.ManyToManyField(related_name='task_reviewers', to='root_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_owner', to='root_app.user')),
            ],
        ),
    ]
